#!/bin/env bash


crep(){
	local FL=(`git ls-files`)
	local fnd
	for f in ${FL[@]};do
		if [ $f = README.md ];then
			fnd=1
			break
		fi
	done
	if [ -z "$fnd" ];then
		git add README.md
		git commit -a -m "0"
	fi
	git branch -M main
	git remote set-url origin git@github.com:$G_USER/$target.git
	git remote add origin git@github.com:$G_USER/$target.git
	git push -u origin main 2>&1| while read ln;do
		if [ "$ln" = "ERROR: Repository not found." ];then
			echo "ERROR: Remote repository not found. \nPlease make the repository, '$target' and reexececute 'git push -u origin main' manually" >&2
		fi
		if [ "${ln:0:17}" = "ERROR: Permission" ];then
			echo $ln
		fi
	done
}


if [ -z "$1" ];then
	PWD="`pwd`"
	if [ "${PWD%/*}" != $HOME/git_project ];then
		echo "ERROR: Current direcotry is not an entry in \$HOME/git_project." >&2
	fi
	target=${PWD##*/}
else
	target=$1
fi

G_USER=`git config user.name`
if [ -z "$G_USER" ];then
	echo "ERROR: Missing user for git. 
Please set user by executing 'git user.name --(global|local) USER_NAME'"
fi

if ! [[ $target =~ ^[0-9A-Za-z_]+$ ]];then
	echo "ERROR: Illeagal name, '$target'"
fi

mkdir -p ~/git_project/$target
cd ~/git_project/$target

if ! [ -d ~/git_project/$target/.git ];then
	echo "# $target" >> README.md
	git init
fi
crep


